export const ADD_PLAYER = 'ADD_PLAYER';
export const CHANGE_NAV_LOCATION = 'CHANGE_NAV_LOCATION';
export const GAME_ENDED = 'GAME_ENDED';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const RESET_GAME = 'RESET_GAME';
export const SET_GAME_CONFIG = 'SET_GAME_CONFIG';
export const SET_WINNERS = 'SET_WINNERS';
export const TOTAL_NEW_GAME_STEPS = 3;
export const NEW_GAME_PROGRESS_STEPS = {
	NO_PLAYERS: 0,
	PLAYERS_ADDED: 1,
	INVALID_CONFIG: 2,
	COMPLETE: 3
};
