export const NAVIGATE_TO = 'NAVIGATE_TO';

export const types = {
	HOME: 'HOME',
	NEW_GAME: 'NEW_GAME',
	GAME_CONFIG: 'GAME_CONFIG',
	GAME_IN_PROGRESS: 'GAME_IN_PROGRESS',
	SETTINGS: 'SETTINGS'
};

export const subTypes = {
	LEADERBOARD: 'LEADERBOARD',
	ADD_SCORES: 'ADD_SCORES',
	ADD_PLAYER_SCORE: 'ADD_PLAYER_SCORE'
};
