export const types = {
	GAME_CONFIG: 'GAME_CONFIG',
	GAME_IN_PROGRESS: 'GAME_IN_PROGRESS',
	HISTORY_DETAIL: 'HISTORY_DETAIL',
	HISTORY: 'HISTORY',
	HOME: 'HOME',
	NEW_GAME: 'NEW_GAME',
	SETTINGS: 'SETTINGS'
};
